
const actionTypes = {
    LOGIN: 'LOGIN',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',
    LOGOUT: 'LOGOUT',
    LOGOUT_ADMIN: 'LOGOUT_ADMIN',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_SUCCESS_ADMIN: 'LOGIN_SUCCESS_ADMIN',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOGIN_FAIL_ADMIN: 'LOGIN_FAIL_ADMIN',

    GET_PRODUCT: 'GET_PRODUCT',
    GET_PRODUCT_QR: 'GET_PRODUCT_QR',
    // USER
    GET_CURRENT: 'GET_CURRENT',
    PUT_ACCOUNT: 'PUT_ACCOUNT',

}

export default actionTypes