
const actionTypes = {
    LOGIN: 'LOGIN',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',
    LOGOUT: 'LOGOUT',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',

    GET_PRODUCT: 'GET_PRODUCT',
    GET_PRODUCT_QR: 'GET_PRODUCT_QR',
    // USER
    GET_CURRENT: 'GET_CURRENT',
    PUT_ACCOUNT: 'PUT_ACCOUNT'
}

export default actionTypes